name: Go Test and Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go get .

      - name: Run tests
        run: go test ./... -json > TestResults-${{ matrix.go-version }}.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json

      - name: Run gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: './...'

      - name: Run go-mod-outdated
        run: |
          go install github.com/psampaz/go-mod-outdated@latest
          go list -u -m -json all | go-mod-outdated -update -direct

      - name: Run nancy
        run: |
          go install github.com/sonatype-nexus-community/nancy@latest
          go list -json -deps | nancy sleuth

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
