name: Build and Publish Docker Image to GHCR

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(git describe --tags --always)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build . \
            -t ghcr.io/${{ github.repository }}/domain-error-go:latest \
            -t ghcr.io/${{ github.repository }}/domain-error-go:${{ steps.get_version.outputs.VERSION }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/domain-error-go:latest
          docker push ghcr.io/${{ github.repository }}/domain-error-go:${{ steps.get_version.outputs.VERSION }}
