name: Build and Publish Docker Image to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(git describe --tags --always)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Prepare Docker image name
        id: prep
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build . \
            -t ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} \
            -f Dockerfile.multistage

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: 'ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.13.4
        with:
          image: ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
