name: Build and Publish Docker Image to GHCR

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$(git describe --tags --always)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Prepare Docker image name
        id: prep
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build . \
            -t ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} \
            -f Dockerfile.multistage

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
